#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

patterns=(
  "Made-with:[[:space:]]*Cursor"
  "Made with Cursor"
  "Generated by Cursor"
  "Generated with Cursor"
  "AI-generated"
  "Generated by ChatGPT"
  "Generated with ChatGPT"
  "Generated by Copilot"
  "Generated with Copilot"
)

tmp_patterns_file="$(mktemp)"
trap 'rm -f "$tmp_patterns_file"' EXIT
printf "%s\n" "${patterns[@]}" > "$tmp_patterns_file"

echo "== Commit message audit =="
if git log --format=%B | rg -n -i -f "$tmp_patterns_file"; then
  echo ""
  echo "Found possible fingerprints in commit messages."
  exit 2
else
  echo "No blocked fingerprint patterns found in commit messages."
fi

echo ""
echo "== Tracked file content audit =="
mapfile -t tracked_files < <(
  git ls-files \
    ':(exclude)scripts/audit-ai-fingerprints.sh' \
    ':(exclude).githooks/commit-msg'
)

if rg -n -i -f "$tmp_patterns_file" "${tracked_files[@]}"; then
  echo ""
  echo "Found possible fingerprints in tracked files."
  exit 3
else
  echo "No blocked fingerprint patterns found in tracked files."
fi
